### ISSUE TITLE
Website not tracked in Google Analytics

### ISSUE THREAD

**Issue by bart-lunika** [thirtybees/ganalytics#1]
The UA-code defined in the admin is not inserted in the front-end script and causes GA not to track the website.

I noticed that after the update Google Analytics did not give results anymore. When viewing the page source there is no UA-code found. Also GA debugging plugin in chrome says no GA tracking code is installed.

**Comment by firstred** [comment]
Pffftt, of all the mistakes that can happen, the two most important lines were accidentally removed!
Sorry about that! Should be restored with an update in a few minutes.

**Comment by bart-lunika** [comment]
Can happen, no worries! I updated the module and now everything is working properly again. The tracking code is in the source code now.
