### ISSUE TITLE
IP anomizer is highly welcome

### ISSUE THREAD

**Issue by pedalracer** [thirtybees/ganalytics#3]
As noted in the roadmap linked here the option to hide IP adress is missing. Without it is not usable in EU.
Suggestion in order to minimize confusion:
Merge both ThirtyBees Google Analytics modules into one with options to hide IP and TAG if wanted.

**Comment by firstred** [comment]
Not sure what you are talking about. That feature already exists AFAIK: https://github.com/thirtybees/ganalytics/blob/master/ganalytics.php#L265-L282

**Comment by Dh42** [comment]
This was added 6 months ago, https://github.com/thirtybees/ganalytics/commit/35b64ed21ec771e55694797d9072f1658fd3bd1b
