### ISSUE TITLE
Missing ; at the end of setTimeout function

### ISSUE THREAD

**Issue by cienislaw** [thirtybees/ganalytics#6]
Missing ; at the end of setTimeout function reveals as a problem when 'Move JS to the end of page' option is enabled.

**Comment by getdatakick** [comment]
Funny one. This should probably be fixed in the core 'Move JS to the end of page' functionality.

**Comment by getdatakick** [comment]
Fixed by commit 4cf78e4bd45bf6a30b152a2a49724fb82d3fb071
